# This is document with teams key attributes

title = "Team registry"

[xhipster]
name = "Dima Starodubcev"
gitcoin = "0x7C4401aE98F12eF6de39aE24cf9fc51f80EBa16B"
payouts = "0x7C4401aE98F12eF6de39aE24cf9fc51f80EBa16B"
github = "xhipster"
telegram = "xhipster"
keybase = "21xhipster"
ipfs = "QmV9P23ZC2GCsDanZwZQHWEKdnd2VyXwzgM5x7XA7iMgnp"
cyber = "cyber1hlu0kqwvxmhjjsezr00jdrvs2k537mqhatjadg"

[dimakorzhovnik]
name = "Dima Korzhovnik"
gitcoin = "0xE8298160C9E8cabd8F2711B92529E0aFE8FB01FB"
payouts = "0xE8298160C9E8cabd8F2711B92529E0aFE8FB01FB"
github = "dimakorzhovnik"
telegram = "korzhovnik_dima"
keybase = "dimakorzhovnik"
ipfs = "QmciKaXo9bSF3BsV2JLponqmrWqbvGiw5qEG6epQsRKFTA"
cyber = "cyber177gvvqtn7xl8qvl6yw4vax9raz80fx66aukc94"
